### ISSUE TITLE
Adding a var causes incorrect output

### ISSUE THREAD

**Issue by scottcha** [microsoft/aurora#24]
I think there is a chance I'm hitting this "Currently, adding one more variable here causes the model to incorrectly load the static variables. It is possible to hack around this. We are working on a more principled fix. Please open an issue if this is a problem for you." So I'm logging an issue to identify the workaround.

Repro steps:
1. Ensure ERA5 data has additional variables beyond the default (I randomly picked the tsn var for this example) & that batch is loading that var. Also precalculate the mean and std for the new var
```
from aurora import normalisation
#extend locations to include the mean of tsn
normalisation.locations["tsn"] = np.float32(surf_vars_ds.tsn.mean().values)
normalisation.scales["tsn"] = np.float32(surf_vars_ds.tsn.std().values)
```

2. Load the pretrained weights
```
pretrained_weights = torch.load("aurora-0.25-small-pretrained.ckpt")
```
3. Adjust the pretrained weights to accommodate the new var & initialize to pretrained weights
```
new_surf_token_embeds_weight = torch.zeros((256, 8, 2, 4, 4))  
new_surf_token_embeds_weight[:, :7, :, :, :] = pretrained_weights['net.encoder.surf_token_embeds.weight']
pretrained_weights['net.encoder.surf_token_embeds.weight'] = new_surf_token_embeds_weight

new_surf_head_weight = torch.zeros((80, 512))  
new_surf_head_weight[:64, :] = pretrained_weights['net.decoder.surf_head.weight']
pretrained_weights['net.decoder.surf_head.weight'] = new_surf_head_weight

new_surf_head_bias = torch.zeros((80,))  
new_surf_head_bias[:64] = pretrained_weights['net.decoder.surf_head.bias']
pretrained_weights['net.decoder.surf_head.bias'] = new_surf_head_bias
```
4. Fixup the names (i have no idea why these come downloaded with "net" prefix which I'm just removing)
```
new_pretrained_weights = {}
for key, value in pretrained_weights.items():
    new_pretrained_weights[key[4:]] = value
```
5. Initialize the model with the extra var
```
from aurora import AuroraSmall

model = AuroraSmall(surf_vars=("2t", "10u", "10v", "msl", "tsn"), use_lora=False)

model.load_state_dict(new_pretrained_weights)
```
6. Make a prediction 
```
from aurora import Aurora, rollout

model.eval()
model = model.to("cuda")

with torch.inference_mode():
    preds = [pred.to("cpu") for pred in rollout(model, batch, steps=2)]

model = model.to("cpu")
```
7. Plot the output of the 2t which was in the original model

![image](https://github.com/user-attachments/assets/433b78ac-512c-4c55-8b66-76c32397565b)

Expected result (plot of 2t using default input vars)

![image](https://github.com/user-attachments/assets/1b0eb633-4299-45cd-bea0-99f5d70829ef)

Its very possible I missed an assumption as part of this process but given the comment referenced above about adding the var and how the output looks I figured there was a chance I was running in to the referenced issue.

Also note that I subsetted the batch input to a smaller input set.  It seemed that this was mostly handled in the model initialization but wanted to note that in case it was related.
Thanks!

**Comment by wesselb** [comment]
Hey @scottcha!

> I think there is a chance I'm hitting this "Currently, adding one more variable here causes the model to incorrectly load the static variables. It is possible to hack around this. We are working on a more principled fix. Please open an issue if this is a problem for you." So I'm logging an issue to identify the workaround.

Yes, I think this is what you're currently running into. :( Apologies for the problems.

[The issue is that the static variable names are concatenated to the surface variable names, and the position in the resulting list is used to identify the parameters.](https://github.com/microsoft/aurora/blob/c81800565cfd72b963ce8834de5c2389e9f59859/aurora/model/encoder.py#L80) Consequently, adding in one more surface variable shifts the positions of the static variables:

```python
        # We treat the static variables as surface variables in the model.
        surf_vars = surf_vars + static_vars if static_vars is not None else surf_vars
        self.surf_var_map = create_var_map(surf_vars)
        self.atmos_var_map = create_var_map(atmos_vars)
```

The workaround is to do something like this:

```python
        # We treat the static variables as surface variables in the model.
        surf_vars = surf_vars[:4] + static_vars + surf_vars[4:] if static_vars is not None else surf_vars
        self.surf_var_map = create_var_map(surf_vars)
        self.atmos_var_map = create_var_map(atmos_vars)
```

It's on our TODO list to refactor this, but this might still take a couple of weeks.

**Comment by scottcha** [comment]
Thanks for that suggestion.  I tried it and unfortunately, I get pretty much the same unexpected results even when I've validated that the order of the surface vars + static vars + new vars is the same.  I'll continue to investigate but it seems there must but something additionally wrong with my assumptions when doing this (i imagine there is something besides the 3 layers in the model which needs to change but which I haven't identified yet).  Any thoughts?

**Comment by wesselb** [comment]
@scottcha you almost got it right! I think that this should work:

```
new_surf_head_weight = torch.zeros((16, 5, 512))  
new_surf_head_weight[:, :4, :] = pretrained_weights['net.decoder.surf_head.weight'].reshape(16, 4, 512)
pretrained_weights['net.decoder.surf_head.weight'] = new_surf_head_weight.reshape(-1, 512)

new_surf_head_bias = torch.zeros((16, 5))  
new_surf_head_bias[:, :4] = pretrained_weights['net.decoder.surf_head.bias'].reshape(16, 4)
pretrained_weights['net.decoder.surf_head.bias'] = new_surf_head_bias.reshape(-1)
```

**Comment by wesselb** [comment]
@scottcha, would you be able to see if #27 works for you?

**Comment by scottcha** [comment]
> @scottcha, would you be able to see if #27 works for you?

@wesselb sure I left this comment in the PR https://github.com/microsoft/aurora/pull/27#issuecomment-2341640976 but so far looks good to the level I'm able to evaluate it.
