### ISSUE TITLE
" Unused Variables B and T on Line 201 in aurora.py"

### ISSUE THREAD

**Issue by qqydss** [microsoft/aurora#28]
In the program file aurora/aurora/model/aurora.py, line 201: B, T = next(iter(batch.surf_vars.values()))[0], it appears that B and T are not utilized in the following code, nor do they seem to represent shape parameters. Could you please provide some clarification on this?
![snippet](https://github.com/user-attachments/assets/de73df2b-b28f-433f-b3d0-56973707a4cc)

**Comment by wesselb** [comment]
Hey @qqydss! Thanks for opening an issue. You're right that this line isn't used and can be removed. We'll do that. Thanks for catching this. :)
