### ISSUE TITLE
Possibility to run LAM setup?

### ISSUE THREAD

**Issue by guidocioni** [microsoft/aurora#40]
I have had this question for a while because it seems that any Neural Network based model can only perform simulations at the resolution and on the same domain it was trained on.
I was wondering if with Aurora the possibility exists to run the model at a smaller grid spacing (and possibly on a limited domain), starting with the same initial condition you'd use for a global simulation.

For example, run a simulation only over Germany at 2 km (instead than 10km) starting from the IFS HRES analysis. Will this work in theory? Can I just provide the model a 2 km interpolated version of the IFS analysis over a limited domain or will it expect a global file?

**Comment by wesselb** [comment]
Hey @guidocioni! My guess is that this will not work out of the box, but that you likely can make it work with some additional fine-tuning. I think this would be a really interesting experiment. If you decide to try it, please report the results back here. :)
