### ISSUE TITLE
Access to Model Checkpoints

### ISSUE THREAD

**Issue by christegho** [microsoft/aurora#41]
Hi Aurora team,

I have submitted a request to access the checkpoints on huggingface more than a week ago and the request status is still pending. I am wondering if there is any way to have access to the models, or whether the access is currently suspended?

Thanks so much!

**Comment by wesselb** [comment]
Hey @christegho! You should be able to get the weights [here](https://huggingface.co/microsoft/aurora) without any login or request.

**Comment by wesselb** [comment]
I will assume that you've been able to acquire the model weights and hence close this issue. Please reopen the issue if you still cannot access the weights.
