### ISSUE TITLE
ERA5 fine-tune verision

### ISSUE THREAD

**Issue by ShileiCao** [microsoft/aurora#48]
Thanks for this awesome work. Any plans to release the checkpoint of the ERA5 fine-tune verision?

**Comment by wesselb** [comment]
Hey @ShileiCao! Thank you. :) We actually have not fine-tuned the model to ERA5. If you wish to make predictions with ERA5 as inputs, I would recommend to use the normal pretrained model.

**Comment by ShileiCao** [comment]
@wesselb  Thanks for your answer. I have another question what is the difference between LevelPatchEmbed and torch.nn.Conv3d ?

**Comment by wesselb** [comment]
`LevelPatchEmbed` is basically a 3D convolution with variable-specific weights. It is indeed implemented with `torch.nn.Conv3d`.
