### ISSUE TITLE
project dependencies are missing xarray and netcdf4

### ISSUE THREAD

**Issue by scottcha** [microsoft/aurora#5]
When following sample instructions you will get errors for missing xarray and netcdf4 dependencies.

Repro steps:
1. Create a clean repo
2. Install via pip
3. Follow steps in example: https://github.com/microsoft/aurora/blob/main/docs/example.ipynb

expected result:
Example works

actual result:
you will first get an error for a missing xarray dependency, after fulfilling that you will then get an error for a missing netcdf4 dependency.

**Comment by wesselb** [comment]
Hey @scottcha! Thanks for noticing this.

You're right that the notebook requires additional packages. I will clarify that in the notebook. :)
